version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    
    command: sleep infinity
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    
    network_mode: host
    
    # Uncomment to connect as root instead
    # user: root
